### ISSUE TITLE
except few distro for example the ubuntu-20.04-gnome, almost all the live CD is not bootable

### ISSUE THREAD

**Issue by braindevices** [netbootxyz/ubuntu-squash#4]
I tried all other ubuntu version, only a few of them can actually work. Others always report `connection reset`, it seems the embedded http has some problem because I can actually download those vmlinuz in my browser.

**Comment by braindevices** [comment]
it seems the KDE ones are most problematic. Others can boot after few retry but KDE ones always fail.

**Comment by braindevices** [comment]
On VM it always worked perfect. But on a real AMD metal it starts to have this problem

**Comment by antonym** [comment]
I was loading the live boot images on an AMD EPYC server last week without any issues, so closing this out.

**Comment by antonym** [comment]
I was loading the live boot images on an AMD EPYC server last week without any issues, so closing this out.
