### ISSUE TITLE
Incorrect squashfs filename for Ubuntu 22.04 amd64

### ISSUE THREAD

**Issue by vrelk** [netbootxyz/ubuntu-squash#5]
The 22.04.1-dc2f0a12 tagged release has the incorrect filename for the filesystem, and therefore cannot be downloaded.

**Comment by antonym** [comment]
Are you using latest release? Rolling and 2.0.61 should both be pulling the 22.04.1 ISO now.

**Comment by vrelk** [comment]
I am unsure of the actual version, but it was from a PXE boot image created
using the ansible playbook provided in the main repo. It was a fresh clone,
done about an hour before I created this issue.

**Comment by antonym** [comment]
There were some recent fixes to the versioning so I would make sure to use the latest version.
